/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as VolumeRouteImport } from './routes/volume'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectStravaRouteImport } from './routes/connect-strava'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities/$activityId'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumeRoute = VolumeRouteImport.update({
  id: '/volume',
  path: '/volume',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectStravaRoute = ConnectStravaRouteImport.update({
  id: '/connect-strava',
  path: '/connect-strava',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coach': typeof CoachRoute
  '/connect-strava': typeof ConnectStravaRoute
  '/dashboard': typeof DashboardRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/volume': typeof VolumeRoute
  '/zones': typeof ZonesRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coach': typeof CoachRoute
  '/connect-strava': typeof ConnectStravaRoute
  '/dashboard': typeof DashboardRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/volume': typeof VolumeRoute
  '/zones': typeof ZonesRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/activities': typeof ActivitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coach': typeof CoachRoute
  '/connect-strava': typeof ConnectStravaRoute
  '/dashboard': typeof DashboardRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/volume': typeof VolumeRoute
  '/zones': typeof ZonesRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/coach'
    | '/connect-strava'
    | '/dashboard'
    | '/fitness'
    | '/login'
    | '/predictions'
    | '/volume'
    | '/zones'
    | '/activities/$activityId'
    | '/auth/callback'
    | '/activities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/coach'
    | '/connect-strava'
    | '/dashboard'
    | '/fitness'
    | '/login'
    | '/predictions'
    | '/volume'
    | '/zones'
    | '/activities/$activityId'
    | '/auth/callback'
    | '/activities'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/coach'
    | '/connect-strava'
    | '/dashboard'
    | '/fitness'
    | '/login'
    | '/predictions'
    | '/volume'
    | '/zones'
    | '/activities/$activityId'
    | '/auth/callback'
    | '/activities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CoachRoute: typeof CoachRoute
  ConnectStravaRoute: typeof ConnectStravaRoute
  DashboardRoute: typeof DashboardRoute
  FitnessRoute: typeof FitnessRoute
  LoginRoute: typeof LoginRoute
  PredictionsRoute: typeof PredictionsRoute
  VolumeRoute: typeof VolumeRoute
  ZonesRoute: typeof ZonesRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume': {
      id: '/volume'
      path: '/volume'
      fullPath: '/volume'
      preLoaderRoute: typeof VolumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-strava': {
      id: '/connect-strava'
      path: '/connect-strava'
      fullPath: '/connect-strava'
      preLoaderRoute: typeof ConnectStravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CoachRoute: CoachRoute,
  ConnectStravaRoute: ConnectStravaRoute,
  DashboardRoute: DashboardRoute,
  FitnessRoute: FitnessRoute,
  LoginRoute: LoginRoute,
  PredictionsRoute: PredictionsRoute,
  VolumeRoute: VolumeRoute,
  ZonesRoute: ZonesRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
